### ISSUE TITLE
Let user have controlled over adding/pushing git tag in prepare stage

### ISSUE THREAD

**Issue by tarazansafak** [semantic-release/exec#17]
Hello,

In the prepare stage, prepare exec step is adding the git tag and pushing it. Let user set if s/he wants to tag or not. At least give user an opportunity to not the push these git tags. This is useful on the way to publishing from feature branches

**Comment by pvdlg** [comment]
That's the core that create the git tag, not the `exec` plugin.
The tag is always created as semantic-release relies on it to figure out what is the last release done so not creating the tag is not really an option.
So every time a release is done, semantic-release create a tag, so on next run it will be able to figure out what commit was added since the last tag.

> This is useful on the way to publishing from feature branches

Can explain what is your use case? 
How creating a tag is problematic if you release on npm?
What would you achieve by having a version released on npm but not tagged in the git repo?

**Comment by tarazansafak** [comment]
I understand your point, however, isn't exec plugin's aim to give user a more freedom and customize what is being run in each steps(prepare, publish etc.)? As tagging in done in "prepare" step. I would like to have full control of it including tagging.

Here is a bit detailed explanation:
Imagine you have master and feature branches. Your master is v1.0.0. On feature branch which was created from master you committed: fix fix feat feat fix in this order. Currently, you will release v1.2.1 from feature branch. When you merge it to master, released version will be correct v1.1.0. Did you see the inconsistency? If I would have control of tagging on git, I would disable it on feature branches. Btw this way we could remove the inconsistency

**Comment by pvdlg** [comment]
The tagging is not done in the prepare step. It's done by the core, after the prepare step and before the publish step.

Once again without tagging there is no way for semantic-release to release all the versions between 1.0.0 to 1.2.1 from your example. Because without the previous version being tagged, semantic-release cannot determine which commits have been added since the last release.

In your example, without tagging the following would happen:
- fix => release 1.0.1, because 1.0.0 (last release tagged) incremented of patch = 1.0.1
- fix => release 1.0.1, because 1.0.0 (last release tagged) incremented of patch = 1.0.1 => npm would errors out
- feat => release 1.1.0, because 1.0.0 (last release tagged) incremented of minor = 1.1.0
- feat => release 1.1.0, because 1.0.0 (last release tagged) incremented of minor = 1.1.0 => npm would errors out
- fix => release 1.0.1, because 1.0.0 (last release tagged) incremented of patch = 1.0.1 => npm would errors out

>  If I would have control of tagging on git, I would disable it on feature branches. Btw this way we could remove the inconsistency

Even if semantic-release had another way to determine the last release (therefore avoiding the errors mentioned above) you would "remove" those inconsistencies in the tagging but you will not remove them in the release on npm.
If you make the commits `fix: A`, `fix: B`, `feat: C`, `feat: D`, `fix: E` you would release on npm from your "feature branch":
- 1.0.1 (with A)
- 1.0.2 (with A and B)
- 1.1.0 (with A, B and C)
- 1.2.0 (with A, B, C and D)
- 1.2.0 (with A, B, C, D and E)

Then after merging to master you would release 1.1.0 (with A, B, C, D and E) that would be inconsistent and also errors out on npm as 1.1.0 was already released and npm doesn't allow to release the same version twice.

**Comment by tarazansafak** [comment]
> In your example, without tagging the following would happen:

You are mistaken here because if there are multible commits, semantic-release is considering the most significant commit and increasing the version accordingly. Thus `fix fix feat feat fix` would give you 1.1.0 assuming that you have initial git tag with v1.0.0. So, there wouldn't be inconsistency. 

> Even if semantic-release had another way to determine the last release (therefore avoiding the errors mentioned above) you would "remove" those inconsistencies in the tagging but you will not remove them in the release on npm.

Actually, I believe latest release should be determined from npm registry with latest dist-tag. This info could be used to initial tagging of feature branches. 

> Then after merging to master you would release 1.1.0 (with A, B, C, D and E) that would be inconsistent and also errors out on npm as 1.1.0 was already released and npm doesn't allow to release the same version twice.

You are right, that's why I am looking for pre-release support which will be implemented in #563.

**Comment by pvdlg** [comment]
> You are mistaken here because if there are multible commits, semantic-release is considering the most significant commit and increasing the version accordingly. Thus fix fix feat feat fix would give you 1.1.0 assuming that you have initial git tag with v1.0.0. So, there wouldn't be inconsistency.

Yes, if you push multiple commits at once, semantic-release will use the most significant commit. However, even if you did not mention in your example if those commits were done one by one or all at once, you mentioned that you start with version `1.0.0` and end up with version`1.2.1`. The only way to achieve this is to make those commit one by one. If would do those commits all at once it would result in version `1.1.0`. Therefore your example implies the commit were done one by one with a release being done for each one. So it doesn't seem I'm mistaken on that one.

> Actually, I believe latest release should be determined from npm registry with latest dist-tag. This info could be used to initial tagging of feature branches.

That's what we used to do but we changed that to use git tags only for several reasons, one of them being that some use a package registry that doesn't provide a way to retrieve the last commit included in the release. Using tags is preferred as it guarantees we'll find the commit associated with the release and it would work with any registry.

> You are right, that's why I am looking for pre-release support which will be implemented in #563.

Yes. Should this is be closed then?
