### ISSUE TITLE
Output is not streamed

### ISSUE THREAD

**Issue by felixfbecker** [semantic-release/exec#38]
I am running webpack with the exec plugin as a prepare step, to avoid running it when no release needs to be done. It can take multiple minutes.

Currently, during the whole time, no output is shown. Once the command finishes, all output is shown at once.

This makes it hard to watch the build progress or determine if it hanged (and CI might kill the build if it does not output anything for longer than 10min).

Expected: Output should be streamed.

Passing `stdio: 'inherit'` to execa (or `stdio: [stdout, stderr]`) should do the trick.

**Comment by pvdlg** [comment]
I tried to do that, but the problem I encountered is that when streaming the output `execa` would close the stream when the command ends.
When the streams are `process.stdout` and `process.stderr` that has no effect because they can't be closed apparently.
However when passing a custom stream (See semantic-release/semantic-release#852 for the motivation of supporting that) `execa` would close the stream and when other stuff in semantic-release tries to write to the stream it would throw an error.
After a bit of research it's not `exaca` directly that closes the stream but `child_process` and I didn't find a way to prevent to close the streams.
