### ISSUE TITLE
Issue with running scripts?

### ISSUE THREAD

**Issue by darewreck54** [semantic-release/exec#81]
Hi, 

I'm having issue with following your example: 

```
 "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    ["@semantic-release/exec", {
      "verifyConditionsCmd": "./verify.sh",
      "publishCmd": "./publish.sh ${nextRelease.version} ${options.branch} ${commits.length} ${Date.now()}"
    }],
  ]
}
```

my verify.sh

`echo 'verifying'`

When i execute it, i get the following:

![image](https://user-images.githubusercontent.com/16171726/64418191-65c65000-d04f-11e9-8f28-24a3bb99940c.png)

Does the verify.sh need to be defined a certain way?  Its also located in the same level as where the .releaserc is set?

Thanks,
Derek

**Comment by pvdlg** [comment]
It's related to your OS that is not capable of figuring out which shell to use to run the script.
Maybe add `#!/bin/bash` at the top of your script.

In any case in order to work the command you configure must be able to be run by your OS.
Currently I imagine that running `./verify.sh` in the terminal of the machine running semantic-release would produce the same error.

**Comment by nunocalaim** [comment]
It would be super useful if people post their full config file
